name: Deployment

"on":
  - push
  - pull_request

permissions: {}

jobs:
  deploy_ghpages:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
      - run: echo "$GITHUB_SHA" >> public/index.html
      - uses: ./
        env:
          BUILD_DIR: public/
          GH_PAT: ${{ secrets.GH_PAT }}
